apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test

resources:
- job.yaml
- serviceaccount.yaml
- rabc.yaml

commonLabels:
  app.kubernetes.io/name: promk8s-resource-operate-jobetheus
  app.kubernetes.io/version: v0.2

images:
- name: lchdzh/k8s-resource-operate-job
  newTag: v0.2